### ISSUE TITLE
awx job_templates launch - --extra_vars parameter - missing = and double-quotes

### ISSUE THREAD

**Issue by wojtaseu** [squillace/porter-ansible#2]
The AWX mixin it’s NOT adding the character `=` in the extra_vars parameter between
--extra_vars and path to the file and double-quotes. This is required as per AnsibleCLI documentation
[awx job_templates launch](https://docs.ansible.com/ansible-tower/latest/html/towercli/reference.html#awx-job-templates-launch)

To reproduce the issue.

1. Try to run job_templates with extra_vars. You can use the below code

```
  - awx:
      description: "Launch parameters"
      arguments: 
        - job_templates
        - launch
      flags:
        id: "{{bundle.parameters.templateID}}"
        extra_vars: "@keyvaultparams.yaml"
        credentials: "1,709,1185,1458"
```

The current behavior
![image](https://user-images.githubusercontent.com/276283/129561375-ee172c9d-e537-4afe-a21c-f35021eac82a.png)

Expected behavior
`awx job_templates launch --credentials 1,709,1185,1458 --extra_vars="@keyvaultparams.yaml" --id 6341`
